### ISSUE TITLE
유튜브를 켤 수 있는 버그가 있습니다.

### ISSUE THREAD

**Issue by minseok128** [yymin1022/CAUKiosk_310#1]
310관 1층 키오스크에서 특정 동작(가장 아래에서 위로 쓸어 올리는 제스처)를 통해 유튜브에 접속할 수 있는 버그가 발견되었습니다. 이를 악용하여 310관 1층 전체에 울리는 블랙핑크 뮤직비디오를 틀어버리는 악용 사례가 발견되었습니다. 빠른 수정 부탁 드립니다. 감사합니다.

- [x] 블랙핑크 뮤직비디오 분석
- [ ] 키오스크 운영체제 제작하고 컴파일
- [ ] 오직 안내 역할만 할 수 있도록 제한

**Comment by yymin1022** [comment]
해당 Issue의 경우, 키오스크 소프트웨어상에서 제어가 불가능하고, OS를 담당한 업체 주관이므로 본 Repository에서 해결할 수 없는 것으로 판단하였습니다.
`블랙핑크 뮤직비디오 분석` To-Do는 정상적으로 수행하였으며, 본 Issue는 Close 하도록 하겠습니다.
감사합니다.
